# Generated by Django 5.2.10 on 2026-01-19 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recoltes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField()),
                ('seuil_alerte', models.FloatField(default=100)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recoltes.culture')),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.entrepot')),
            ],
        ),
    ]
